---
title: "traffic-spatial"
author: "Peter Silverstein"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE}
# Loading Libraries

# General Use
library(tidyverse)
library(ggplot2)
library(here)
library(keyring)
library(stringr)

# GIS and Mapping
library(sf)
library(tmap)

# Census
library(tidycensus)
```

# Functions
## Traffic Function
```{r}
get_weighted_traffic_average <- function(route_id) {
  route_shape <- routes_subset %>%
    filter(ROUTE_ID == route_id)
  buffered_route <- st_buffer(route_shape, dist = 1)
  intersection <- st_intersection(congestion_spatial, buffered_route)
  intersection_line <- st_collection_extract(intersection, "LINESTRING")
  
  processed_intersection <- intersection_line %>%
    mutate(length = units::set_units(st_length(geometry), "m", mode = "standard")) %>% # Calculate length of each segment
    filter(length > units::set_units(5, "m", mode = "standard")) # Filtering out any segment less than 5m in length to remove noise

  total_length <- sum(processed_intersection$length)
  
  processed_intersection <- processed_intersection %>%
    mutate(wgt_traffic = AWDT * (length / total_length))
  
  segment_traffic <- as.numeric(sum(processed_intersection$wgt_traffic))
  return(segment_traffic)
}
```

## Ridership Function
```{r}
get_weighted_transit_ridership <- function(route_id) {
  route_shape <- routes_subset %>%
    filter(ROUTE_ID == route_id)
  buffered_route <- st_buffer(route_shape, dist = 402) # approximate 0.25 mile buffer
  
  # Filter ACS polygons to include only ones with over 50% within buffer
  blocks_filtered <- kcacs_blocks %>%
    filter(lengths(st_intersects(., buffered_route)) > 0) %>%
    rowwise() %>%
    mutate(
      inter_geom = list(st_intersection(geometry, buffered_route)),
      inter_area = {
        ig <- inter_geom[]
        if(length(ig) == 0 || all(st_is_empty(ig))) {
          0
          } else {
            sum(st_area(ig))
            }
        },
      total_area = st_area(geometry),
      overlap_ratio = as.numeric(inter_area / total_area)
      ) %>%
    ungroup() %>%
    filter(overlap_ratio >= 0.5)
  
  # Weighted average
  total_population <- sum(blocks_filtered$tot_popE)
  
  blocks_filtered <- blocks_filtered %>%
    mutate(wgt_pop = transp_mthd_public_perc * (tot_popE/total_population))
  
  route_ridership <- as.double(sum(blocks_filtered$wgt_pop))
  return(route_ridership)
}
```

# Loading Data

## Load route_ids
```{r}
routes <- read.csv("Predictor Data Sets/gtfs-static-files/routes.txt") %>%
  filter(agency_id == 1) %>% # Filtering to only include King County Metro agency
  select(route_id, route_short_name) %>%
  mutate(rapid_ride = case_when(
    str_detect(route_short_name, "Line") ~ 1,
    TRUE ~ 0
  )) %>%
  mutate(route_id = as.factor(route_id),
         rapid_ride = as.factor(rapid_ride)) 
  
routes
```

## Load route shapes, confirm CRS
```{r}
# Current CRS NAD83
kc_route_shp <- st_read(here("Predictor Data Sets",
                           "KCMetro_Transit_Lines",
                           "Transit_Routes_for_King_County_Metro___transitroute_line.shp")) %>%
  select(ROUTE_ID, geometry) %>%
  distinct(ROUTE_ID, .keep_all = TRUE) %>%
  mutate(ROUTE_ID = as.factor(ROUTE_ID))

# Joining
routes_shp <- kc_route_shp %>%
  left_join(routes,
            by = c("ROUTE_ID" = "route_id")) %>%
  st_transform(crs = 32610)

routes_shp
```

## Load spatial traffic shapefile
```{r}
normalize <- function(x, na.rm = TRUE) {
  return((x - min(x)) / (max(x) - min(x)))
}

# CRS is NAD83
# Scaling AWDT with z-scores so "average" traffic is 0, heavier traffic is positive, lighter is negative
congestion_spatial <- st_read(here("Predictor Data Sets",
                                   "2018_Traffic_Flow_Counts-shp",
                                   "2018_Traffic_Flow_Counts.shp")) %>%
  select(AWDT, geometry) %>%
  mutate(across(AWDT, scale)) %>%
  st_transform(crs = 32610)
```

# Load ACS Ridership
```{r}
# Using keyring package to keep my API key hidden
tidycensus_api_key <- key_get(service = "tidycensus_API", username = "my_tidycensus")
census_api_key(tidycensus_api_key)

ACSlist <- load_variables(2022, "acs5", cache = TRUE)

# Projection is NAD83(!!)
kingcounty_acs_blocks <- get_acs(state = "WA",
                                 county = "King",
                                 geography = "block group",
                                 variables = c(tot_pop = "B01003_001",
                                               transp_basetotal = "B08134_001",
                                               transp_mthd_public = "B08134_061"),
                                 geometry = TRUE,
                                 keep_geo_vars = TRUE,
                                 year = 2023,
                                 output = "wide") %>%
  filter(ALAND != 0) %>% # Filter tracts that are 100% water
  mutate(GEOID = as.double(GEOID))

kcacs_blocks <- kingcounty_acs_blocks %>%
  mutate(ALAND_miles = ALAND/2589988) %>% # Converting sq meters to sq miles
  mutate(transp_mthd_public_perc = transp_mthd_publicE / transp_basetotalE) %>%
  select(tot_popE,
         transp_mthd_public_perc,
         geometry) %>%
  st_transform(crs = 32610)
```

# Final Dataset
```{r}
# Filtering dataset to work with my spatial congestion dataset
ylims <- c(5260550, 5286967)
xlims <- c(543840.2, 557439.2)
box_coords <- tibble(x = xlims, y = ylims) %>% 
  st_as_sf(coords = c("x", "y")) %>% 
  st_set_crs(st_crs(routes_shp))

bounding_box <- st_bbox(box_coords) %>% st_as_sfc()

routes_subset <- st_filter(routes_shp, bounding_box, .predicate = st_within) # We lose almost 100 routes, but I think that's ok

route_predictors <- routes_subset %>%
  rowwise() %>%
  mutate(
    spatial_traffic = get_weighted_traffic_average(ROUTE_ID),
    ridership_perc = get_weighted_transit_ridership(ROUTE_ID)
  ) %>%
  ungroup() %>%
  st_set_crs(st_crs(routes_subset))

write_csv(route_predictors, "predictor_tables/route_predictors.csv")
```





