---
title: "stop-level-predictors"
author: "Peter Silverstein"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE}
# Loading Libraries

# General Use
library(tidyverse)
library(ggplot2)
library(here)
library(keyring)
library(lubridate)
library(rstanarm)

# PostgreSQL
library(DBI)
library(RPostgres)

# GIS and Mapping
library(sf)
library(lwgeom) 
```

# Arrival Delay

## Importing Data From SQL, filtering, cleaning
```{r}
# Loading Data
con <- dbConnect(RPostgres::Postgres(),
                 dbname = "sea-gtfs-data",
                 host = "localhost",
                 port = 5432,
                 user = "postgres",
                 password = "Parkour")

gtfs_realtime <- dbReadTable(con, "sea_gtfs_data")
gtfs_realtime <- tibble(gtfs_realtime)

# Filtering Data Outside the Bounding Box (see route-level-predictors)
route_predictors <- read_csv("predictor_tables/route_predictors.csv")
routes_within_bb <- as.numeric(route_predictors$ROUTE_ID)

gtfs_realtime <- gtfs_realtime %>%
  filter(route_id %in% routes_within_bb)

# Filtering out duplicates and future projections
gtfs_main <- gtfs_realtime %>%
  filter(projection == FALSE) %>%
  distinct(trip_id, stop_id, arrival_datetime, .keep_all = TRUE) %>%
  select(trip_id, route_id, stop_id, arrival_datetime, departure_datetime, pull_datetime) %>%
  mutate(trip_id = as.factor(trip_id),
         route_id = as.factor(route_id),
         stop_id = as.factor(stop_id)) %>%
  mutate(arrival_datetime = with_tz(arrival_datetime, "America/Los_Angeles"),
         departure_datetime = with_tz(departure_datetime, "America/Los_Angeles"),
         pull_datetime = with_tz(pull_datetime, "America/Los_Angeles"))

print(paste("Number of rows reduced from", nrow(gtfs_realtime), "to", nrow(gtfs_main)))
```
## Importing scheduled stop times, joining to main, calculating delay
```{r}
# Helper function for dealing with hh > 23 in schedule file
roll_over <- function(time_str) {
  # Split the time string into hours, minutes, seconds
  parts <- as.numeric(strsplit(time_str, ":")[[1]])
  total_seconds <- parts[1] * 3600 + parts[2] * 60 + parts[3]
  # Use modulo operator to get seconds within a day
  remainder <- total_seconds %% 86400
  # Convert remainder seconds back into hh:mm:ss format
  sprintf("%02d:%02d:%02d", 
          remainder %/% 3600, 
          (remainder %% 3600) %/% 60, 
          remainder %% 60)
}

# Importing scheduled stop times
stop_times <- read_csv("Predictor Data Sets/gtfs-static-files/stop_times.txt") %>%
  select(trip_id, arrival_time, departure_time, stop_id, stop_sequence, shape_dist_traveled) %>%
  mutate(trip_id = as.factor(trip_id),
         stop_id = as.factor(stop_id),
         arrival_time = as.character(arrival_time),
         departure_time = as.character(departure_time)) %>%
  rename(sched_arrival_time = arrival_time,
         sched_departure_time = departure_time) %>%
   mutate(
    sched_arrival_time = sapply(sched_arrival_time, roll_over),
    sched_departure_time = sapply(sched_departure_time, roll_over),
    sched_arrival_time = hms::as_hms(sched_arrival_time),
    sched_departure_time = hms::as_hms(sched_departure_time)
  ) %>%
  distinct(trip_id, stop_id, .keep_all = TRUE)

# Joining to main
gtfs_main_withdelays <- gtfs_main %>%
  left_join(stop_times, by = c("trip_id" = "trip_id",
                              "stop_id" = "stop_id")) %>%
  mutate(actual_arrival_time = hms::as_hms(format(with_tz(arrival_datetime, "America/Los_Angeles"), "%H:%M:%S")),
         actual_departure_time = hms::as_hms(format(with_tz(departure_datetime, "America/Los_Angeles"), "%H:%M:%S")),
         date = as.POSIXct(format(with_tz(arrival_datetime, "America/Los_Angeles"), "%Y-%m-%d"))) %>%
  mutate(arrival_delay = as.numeric(actual_arrival_time - sched_arrival_time)) %>%
  mutate(arrival_delay = ifelse(
    arrival_delay < 80000, arrival_delay,
    arrival_delay - 86400
    )) %>%
  select(date, 
         trip_id, 
         route_id, 
         stop_id, 
         sched_arrival_time, 
         sched_departure_time,
         actual_arrival_time,
         actual_departure_time,
         arrival_delay,
         stop_sequence,
         shape_dist_traveled,
         pull_datetime)
```

# Temporal Traffic

```{r}
# Loading data
congestion_temporal <- read_csv("Predictor Data Sets/Traffic_Count_Studies_by_Hour_Bins-2.csv")

# Converting times, setting up day/hour lookup
congestion_dayhour <- congestion_temporal %>%
  filter(TOTAL > 0) %>%
  mutate(datetime = as.POSIXct(ADD_DTTM, 
                               format = "%m/%d/%Y %I:%M:%S %p", 
                               tz = "America/Los_Angeles")) %>%
  filter(datetime > as.POSIXct("01-01-2015 00:00:00", 
                               format = "%m-%d-%Y %H:%M:%S",
                               tz = "America/Los_Angeles")) %>% # Filtering to last 10 years
  filter(datetime < as.POSIXct("01-31-2020 00:00:00", 
                               format = "%m-%d-%Y %H:%M:%S",
                               tz = "America/Los_Angeles") |
           datetime > as.POSIXct("12-31-2021 23:59:59", 
                               format = "%m-%d-%Y %H:%M:%S",
                               tz = "America/Los_Angeles")) %>% # Filtering to remove peak pandemic
  group_by(WEEKDAY) %>%
  summarize(HR01 = mean(HR01_TOTAL),
            HR02 = mean(HR02_TOTAL),
            HR03 = mean(HR03_TOTAL),
            HR04 = mean(HR04_TOTAL),
            HR05 = mean(HR05_TOTAL),
            HR06 = mean(HR06_TOTAL),
            HR07 = mean(HR07_TOTAL),
            HR08 = mean(HR08_TOTAL),
            HR09 = mean(HR09_TOTAL),
            HR10 = mean(HR10_TOTAL),
            HR11 = mean(HR11_TOTAL),
            HR12 = mean(HR12_TOTAL),
            HR13 = mean(HR13_TOTAL),
            HR14 = mean(HR14_TOTAL),
            HR15 = mean(HR15_TOTAL),
            HR16 = mean(HR16_TOTAL),
            HR17 = mean(HR17_TOTAL),
            HR18 = mean(HR18_TOTAL),
            HR19 = mean(HR19_TOTAL),
            HR20 = mean(HR20_TOTAL),
            HR21 = mean(HR21_TOTAL),
            HR22 = mean(HR22_TOTAL),
            HR23 = mean(HR23_TOTAL),
            HR24 = mean(HR24_TOTAL)) %>%
  mutate(WEEKDAY_NAME = case_when(
    WEEKDAY == 1 ~ "Monday",
    WEEKDAY == 2 ~ "Tuesday",
    WEEKDAY == 3 ~ "Wednesday",
    WEEKDAY == 4 ~ "Thursday",
    WEEKDAY == 5 ~ "Friday",
    WEEKDAY == 6 ~ "Saturday",
    WEEKDAY == 7 ~ "Sunday")) %>%
  mutate(AVG_VOL = select(., HR01:HR24) %>% rowMeans(na.rm = TRUE)) %>%
  relocate(WEEKDAY_NAME, .after = WEEKDAY) %>%
  relocate(AVG_VOL, .after = WEEKDAY_NAME)

# Setting up longer format
congestion_dh_longer <- congestion_dayhour %>%
  select(WEEKDAY_NAME, HR01:HR24) %>%
  pivot_longer(cols = -WEEKDAY_NAME,
               names_to = "HOUR",
               values_to = "avg_traffic_dayhour") %>%
  mutate(HOUR = as.numeric(gsub("[^0-9]","", HOUR)))

# Joining
gtfs_main_withcongestion <- gtfs_main_withdelays %>%
  mutate(WEEKDAY = weekdays(date),
         HR = (as.numeric(sched_arrival_time) %/% 3600) + 1) %>%
  left_join(select(.data = congestion_dayhour, WEEKDAY_NAME, AVG_VOL), 
            by = c("WEEKDAY" = "WEEKDAY_NAME")) %>%
  left_join(congestion_dh_longer,
            by = c("WEEKDAY" = "WEEKDAY_NAME",
                   "HR" = "HOUR")) %>%
    rename("weekday" = "WEEKDAY",
         "hr" = "HR",
         "avg_traffic_day" = "AVG_VOL")
```

# Setting up stop sequence and distance travelled
```{r}
seq_standardized <- read.csv("Predictor Data Sets/gtfs-static-files/stop_times.txt") %>%
  select(trip_id, stop_sequence) %>%
  group_by(trip_id) %>%
  arrange(stop_sequence) %>%
  mutate(new_seq = row_number()) %>%
  ungroup() %>%
  arrange(trip_id, stop_sequence) %>%
  mutate(stop_sequence = as.numeric(stop_sequence),
         trip_id = as.factor(trip_id))

gtfs_main_final <- gtfs_main_withcongestion %>%
  inner_join(seq_standardized, 
            by = c("stop_sequence" = "stop_sequence",
                   "trip_id" = "trip_id"))

gtfs_main_final <- gtfs_main_final[, c("date",
                                       "route_id",
                                       "trip_id",
                                       "stop_id",
                                       "sched_arrival_time",
                                       "sched_departure_time",
                                       "actual_arrival_time",
                                       "actual_departure_time",
                                       "arrival_delay",
                                       "stop_sequence",
                                       "new_seq",
                                       "shape_dist_traveled",
                                       "pull_datetime",
                                       "weekday",
                                       "hr",
                                       "avg_traffic_day",
                                       "avg_traffic_dayhour")]

gtfs_main_final
```

# Final Dataset
```{r}
stop_predictors <- gtfs_main_final %>%
  select(route_id, stop_id, arrival_delay, new_seq, shape_dist_traveled, weekday, hr, avg_traffic_dayhour) %>%
  mutate(weekday = as.factor(weekday))

write_csv(stop_predictors, "predictor_tables/stop_predictors.csv")
```

# Standardizing Final Dataset
```{r}
# Standardize function (note that it's 2*sd)
standardize <- function(x) {
  (x - mean(x, na.rm = TRUE)) / (2*sd(x, na.rm = TRUE))
}
stop_pred_std <- stop_predictors %>%
  select(route_id, stop_id, arrival_delay, new_seq, shape_dist_traveled, avg_traffic_dayhour) %>%
  mutate(across(c("new_seq", "shape_dist_traveled", "avg_traffic_dayhour"), standardize))

write_csv(stop_pred_std, "predictor_tables/stop_pred_std.csv")
```

# Checking for NAs
```{r}
# Arrival Times
gtfs_arrival_NAs <- gtfs_main_final %>%
  filter(is.na(arrival_delay))

if (nrow(gtfs_arrival_NAs) == 0) {
    message("The filter returned an empty data frame")
} else {
  gtfs_arrival_NAs
}

# Appears to always be connected to no data/actual arrival time. My best guess is that these are skipped stops or cancelled trips.
# Represents 1.38% of the dataset as of 03.05.2025 (20,478 rows)
```

```{r}
# route_id, stop_id
gtfs_ids_NAs <- gtfs_main_final %>%
  filter(is.na(stop_id))

if (nrow(gtfs_ids_NAs) == 0) {
    message("The filter returned an empty data frame")
} else {
  gtfs_ids_NAs
}

# Empty for both route_id and stop_id as of 03.05.2025
```

```{r}
# new_seq
gtfs_seq_NAs <- gtfs_main_final %>%
  filter(is.na(new_seq))

if (nrow(gtfs_seq_NAs) == 0) {
    message("The filter returned an empty data frame")
} else {
  gtfs_seq_NAs
}

# Empty as of 03.05.2025
```

```{r}
# shape_dist_traveled
gtfs_dist_NAs <- gtfs_main_final %>%
  filter(is.na(shape_dist_traveled))

if (nrow(gtfs_dist_NAs) == 0) {
    message("The filter returned an empty data frame")
} else {
  gtfs_dist_NAs
}

# Empty as of 03.05.2025
```

```{r}
# avg_traffic_dayhour
gtfs_traf_NAs <- gtfs_main_final %>%
  filter(is.na(avg_traffic_dayhour) & !is.na(date))

if (nrow(gtfs_traf_NAs) == 0) {
    message("The filter returned an empty data frame")
} else {
  gtfs_traf_NAs
}

# Empty as of 03.05.2025
```













