
FROM gcr.io/deeplearning-platform-release/r-cpu:latest

# Install necessary R packages
RUN R -e "install.packages(c('remotes'), repos='https://cran.rstudio.com/')"
RUN R -e "remotes::install_github('vdorie/dbarts')"
RUN R -e "remotes::install_github('vdorie/stan4bart')"
# Add any other packages your training needs

# Copy R scripts
COPY Train.R /
COPY train_data.csv

# Set working directory
WORKDIR /

# Set entrypoint to be used by Vertex AI
ENTRYPOINT ["Rscript"]